### ISSUE TITLE
Make a block of contact information

### ISSUE THREAD

**Issue by Vasyl-Smyrechynskyi** [VasylSVR/homepage#4]
Social network links (Facebook or Instagram, etc.), phone number, or email address, and more. Maybe not all links in the world, but only those that are really relevant.

**Comment by korolmarina** [comment]
Email: vasyl.smyrechynskyi@gmail.com
Phone: +380 93 281 88 22 (Telegram)
LinkedIn: https://www.linkedin.com/in/ vasyl-smyrechynskyi-221608176
Skype: smirechvas

**Comment by Vasyl-Smyrechynskyi** [comment]
Thanks! It's done.
