### ISSUE TITLE
Make an CV objective

### ISSUE THREAD

**Issue by Vasyl-Smyrechynskyi** [VasylSVR/homepage#5]
Describe what is the CV purpose (job, studying, internship, etc.)

**Comment by korolmarina** [comment]
O B J E C T I V E
To work in a company where I will use my skills and knowledge gained throughout an almost two-year programming experience to deliver good results, as well as further enhance my skills in the field of software development.

**Comment by Vasyl-Smyrechynskyi** [comment]
Good work!
