### ISSUE TITLE
Get a photo for avatar

### ISSUE THREAD

**Issue by Vasyl-Smyrechynskyi** [VasylSVR/homepage#6]
Chose a photo  for the person visual presentation

**Comment by korolmarina** [comment]
![IMG_20200402_212556](https://user-images.githubusercontent.com/58749210/80925415-39a6ce80-8d98-11ea-8a81-9c5051c33cd5.jpg)

**Comment by Vasyl-Smyrechynskyi** [comment]
Wow! Who is it?
