### ISSUE TITLE
Obtain the work experience block information

### ISSUE THREAD

**Issue by Vasyl-Smyrechynskyi** [VasylSVR/homepage#7]
List work experience with detailed position responsibilities information

**Comment by korolmarina** [comment]
W O R K   E X P E R I E N C E  

 
POWER ENGINEER
Private company “Almaz-M” / May 2015 – May 2018
• Development of the electrical and mechanical part of the plant for replacing natural gas with solid biofuels for “MetInvest Holding”, Kryvyi Rig
• Staff management
• Development of electrical schemas,
• Introduction of automatic control systems,
• Development of technological and operational instructions for staff, as well as instructions on occupational safety
• Staff management

XAMARIN MOBILE AND NODE.JS SOFTWARE ENGINEER
AltexSoft April 2019 – April 2020
Development and support apps from scratch to release, troubleshooting, estimations, teamwork, reports, improvement software performance, work with customers or departments on technical issues

**Comment by Vasyl-Smyrechynskyi** [comment]
You are the Best
