### ISSUE TITLE
Obtain qualifications information

### ISSUE THREAD

**Issue by Vasyl-Smyrechynskyi** [VasylSVR/homepage#8]
List technologies, languages, key skills, etc.

**Comment by korolmarina** [comment]
Q U A L I F I C A T I O N S

PROGRAMMING LANGUAGES:
C#, JavaScript, Dart

TECHNOLOGIES:
Xamarin.Android 
Android platform, MvvmCross, IoC, WorkManager, Restfull API
Project: 
Corporative devices’ monitoring app.  (scanner, location, devices, and users authorization, local notifications)
Node.js
Express.js, Passport.js, Sequelize ORM, Pug, Nodemailer, Telegraf, Auth2, Telegram API, Heroku
Projects: 
- Company informational Telegram Bot to coordinate stuff with web admin panel.
- Technical support Telegram bot. (clients communication with a technical department,   
creation tickets, managing issues states, responses, reports notifications)
Flutter
Bloc pattern, FireBase
Project: Organizer app with rich UI

RESPONSIBILITIES:
•	development and modification of software, fix errors, improvement software performance
•	implementation of software documentation
•	consultation on project status and proposals
•	work with customers or departments on technical issues

KEY SKILLS:
OOP, SOLID
RESTful API
Telegram API
Gitlab, CI/CD
DB`s: PostgreSQL, FireBase, MS SQL
 Server
Agile/Scrum

L A N G U A G E S
English - Intermediate 
Ukrainian - native
Russian - native

**Comment by Vasyl-Smyrechynskyi** [comment]
Thanks.
